---
- name: Deploy OPA Plan Change Window Policy
  hosts: "{{ opa_server | default('all') }}"
  gather_facts: yes
  become: yes

  pre_tasks:  
  # date input format: "2024-07-02 23:14:46"

  roles:
    - role: ssa_demo.opa_server.deploy_opa_policies
      vars:
        policy_files:
          - name: "project_scm_branch"
            template: "project_scm_branch.rego.j2"
            dest_file: "project_scm_branch.rego"
          - name: "jt_naming_validation"
            template: "jt_naming_validation.rego.j2"
            dest_file: "jt_naming_validation.rego"
            